# These categories will be applied to all DAGs in the repo.
categories:
  - ETL/ELT
  - Data Processing
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/dbt_advanced_utility.py
  - path: dags/dbt_advanced.py
  - path: dags/dbt_basic.py
